[tool.poetry]
name = "portal"
version = "0.0.1"
description = ""
authors = ["Simon Janssen <janssen.simon@posteo.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.7.0"
torchvision = "^0.22.0"
onnx = "^1.17.0"
onnxruntime-gpu = "^1.22.0"
onnxslim = "^0.1.52"
httpx = "^0.28.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
timm = "^1.0.15"
ultralytics = "^8.3.131"
ruff = "^0.11.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
